theme = "ayu_dark"

[editor]
line-number = "absolute"
auto-save = true
cursorline = true
gutters = ["diagnostics", "line-numbers", "spacer", "diff"]
completion-trigger-len = 2

inline-diagnostics.cursor-line = "disable"
lsp.display-inlay-hints = false

auto-pairs = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["version-control", "position"]

[keys.normal]
C-s = ":w"

[keys.insert]
