format = '$directory$git_branch$git_status$python$character'

add_newline = false

[directory]
format = '[$path]($style)'
style = 'bold yellow'
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = ' git:\([$branch]($style)\)'
style = 'bold cyan'

[git_status]
format = '[$modified]($style)'
style = 'bold yellow'
modified = '*'
ahead = ''
behind = ''
diverged = ''
untracked = ''
staged = ''
renamed = ''
deleted = ''
conflicted = ''

[python]
format = ' \([$virtualenv]($style)\)'
style = 'bold green'
detect_files = []
detect_extensions = []
detect_folders = []

[character]
success_symbol = ' [\$](bold white)'
error_symbol = ' [\$](bold red)'
